package com.careerfit.backend.config.security;

import com.careerfit.backend.config.AppProperties;
import io.jsonwebtoken.*;
import io.jsonwebtoken.security.Keys;
import io.jsonwebtoken.security.SecurityException;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

import javax.crypto.SecretKey;
import java.nio.charset.StandardCharsets;
import java.util.Date;
import java.util.UUID;

/**
 * JWT token creation, validation and claims extraction.
 * Uses JJWT 0.12.x API (Builder-based).
 */
@Service
public class JwtService {

    private static final Logger log = LoggerFactory.getLogger(JwtService.class);

    private final SecretKey key;
    private final long expirationMs;

    public JwtService(AppProperties props) {
        this.key = Keys.hmacShaKeyFor(props.getJwtSecret().getBytes(StandardCharsets.UTF_8));
        this.expirationMs = props.getJwtExpirationMs();
    }

    /** Generate JWT for an authenticated user and bind it to that account instance. */
    public String generateToken(String subject, String role, UUID userId) {
        return Jwts.builder()
                .subject(subject)
                .claim("role", role)
                .claim("userId", userId.toString())
                .issuedAt(new Date())
                .expiration(new Date(System.currentTimeMillis() + expirationMs))
                .signWith(key)
                .compact();
    }

    /**
     * Legacy helper retained for callers that only need to create a syntactically valid token.
     * Protected endpoints require the account-bound token generated by the overload above.
     */
    @Deprecated
    public String generateToken(String subject, String role) {
        return Jwts.builder()
                .subject(subject)
                .claim("role", role)
                .issuedAt(new Date())
                .expiration(new Date(System.currentTimeMillis() + expirationMs))
                .signWith(key)
                .compact();
    }

    /** Extract subject (email) from token. Throws on invalid/expired token. */
    public String extractSubject(String token) {
        return parseClaims(token).getSubject();
    }

    public String extractRole(String token) {
        return (String) parseClaims(token).get("role");
    }

    public String extractUserId(String token) {
        return parseClaims(token).get("userId", String.class);
    }

    public boolean isTokenValid(String token) {
        return validateToken(token).valid();
    }

    public JwtValidationResult validateToken(String token) {
        if (token == null || token.isBlank()) {
            return JwtValidationResult.invalid("TOKEN_MISSING", "Bearer token is missing");
        }
        try {
            parseClaims(token);
            return JwtValidationResult.ok();
        } catch (ExpiredJwtException e) {
            log.debug("JWT expired: {}", e.getMessage());
            return JwtValidationResult.invalid("TOKEN_EXPIRED", "Token has expired");
        } catch (MalformedJwtException | UnsupportedJwtException e) {
            log.debug("JWT malformed/unsupported: {}", e.getMessage());
            return JwtValidationResult.invalid("TOKEN_INVALID", "Token is invalid");
        } catch (SecurityException e) {
            log.debug("JWT signature invalid: {}", e.getMessage());
            return JwtValidationResult.invalid("TOKEN_INVALID", "Token signature is invalid");
        } catch (JwtException | IllegalArgumentException e) {
            log.debug("JWT validation failed: {}", e.getMessage());
            return JwtValidationResult.invalid("TOKEN_INVALID", "Token is invalid");
        }
    }

    private Claims parseClaims(String token) {
        return Jwts.parser()
                .verifyWith(key)
                .build()
                .parseSignedClaims(token)
                .getPayload();
    }

    public record JwtValidationResult(boolean valid, String code, String message) {
        static JwtValidationResult ok() {
            return new JwtValidationResult(true, null, null);
        }

        static JwtValidationResult invalid(String code, String message) {
            return new JwtValidationResult(false, code, message);
        }
    }
}
