spring:
  config:
    activate:
      on-profile: dev

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  mail:
    enabled: false # Use NoOpMailService in DEV

logging:
  level:
    com.careerfit: DEBUG
    org.springframework.security: DEBUG
