CREATE TABLE IF NOT EXISTS skills (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    canonical_key   VARCHAR(100) NOT NULL,
    name            VARCHAR(100) NOT NULL,
    normalized_name VARCHAR(100) NOT NULL,
    search_text     TEXT NOT NULL,
    category        VARCHAR(50) NOT NULL,
    popularity      INTEGER NOT NULL DEFAULT 0,
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_skills_canonical_key UNIQUE (canonical_key),
    CONSTRAINT uq_skills_normalized_name UNIQUE (normalized_name),
    CONSTRAINT ck_skills_popularity_non_negative CHECK (popularity >= 0)
);

CREATE INDEX IF NOT EXISTS idx_skills_active_prefix
    ON skills (normalized_name text_pattern_ops)
    WHERE is_active = TRUE;

-- canonical_key values shared with matching/skill-transfer-model.json keep
-- manual input consistent with the Potential knowledge model. Extra catalog
-- entries remain valid input even when they have no transfer edge yet.
INSERT INTO skills (canonical_key, name, normalized_name, search_text, category, popularity)
VALUES
    ('java', 'Java', 'java', 'java jvm', 'LANGUAGE', 100),
    ('javascript', 'JavaScript', 'javascript', 'javascript js ecmascript', 'LANGUAGE', 99),
    ('typescript', 'TypeScript', 'typescript', 'typescript ts', 'LANGUAGE', 98),
    ('python', 'Python', 'python', 'python', 'LANGUAGE', 97),
    ('csharp', 'C#', 'c#', 'c# c sharp csharp', 'LANGUAGE', 91),
    ('cpp', 'C++', 'c++', 'c++ cpp', 'LANGUAGE', 88),
    ('go', 'Go', 'go', 'go golang go language go developer go engineer', 'LANGUAGE', 90),
    ('kotlin', 'Kotlin', 'kotlin', 'kotlin jvm android', 'LANGUAGE', 84),
    ('php', 'PHP', 'php', 'php', 'LANGUAGE', 82),
    ('ruby', 'Ruby', 'ruby', 'ruby', 'LANGUAGE', 70),
    ('scala', 'Scala', 'scala', 'scala jvm', 'LANGUAGE', 67),
    ('rust', 'Rust', 'rust', 'rust systems programming', 'LANGUAGE', 72),
    ('dart', 'Dart', 'dart', 'dart flutter', 'LANGUAGE', 70),
    ('swift', 'Swift', 'swift', 'swift ios', 'LANGUAGE', 74),
    ('html', 'HTML', 'html', 'html html5', 'FRONTEND', 96),
    ('css', 'CSS', 'css', 'css css3', 'FRONTEND', 96),
    ('sass', 'Sass', 'sass', 'sass scss', 'FRONTEND', 73),
    ('react', 'React', 'react', 'react react.js reactjs', 'FRONTEND', 98),
    ('vue', 'Vue.js', 'vue.js', 'vue vue.js vuejs', 'FRONTEND', 85),
    ('angular', 'Angular', 'angular', 'angular', 'FRONTEND', 86),
    ('nextjs', 'Next.js', 'next.js', 'next.js next js nextjs', 'FRONTEND', 90),
    ('redux', 'Redux', 'redux', 'redux redux toolkit', 'FRONTEND', 80),
    ('tailwind', 'Tailwind CSS', 'tailwind css', 'tailwind tailwindcss tailwind css', 'FRONTEND', 88),
    ('bootstrap', 'Bootstrap', 'bootstrap', 'bootstrap', 'FRONTEND', 78),
    ('vite', 'Vite', 'vite', 'vite', 'FRONTEND', 79),
    ('webpack', 'Webpack', 'webpack', 'webpack', 'FRONTEND', 75),
    ('nodejs', 'Node.js', 'node.js', 'node.js node js nodejs', 'BACKEND', 96),
    ('springboot', 'Spring Boot', 'spring boot', 'spring spring boot springboot spring mvc', 'BACKEND', 94),
    ('dotnet', '.NET', '.net', '.net dotnet asp.net aspnet', 'BACKEND', 89),
    ('django', 'Django', 'django', 'django', 'BACKEND', 82),
    ('fastapi', 'FastAPI', 'fastapi', 'fastapi fast api', 'BACKEND', 81),
    ('flask', 'Flask', 'flask', 'flask', 'BACKEND', 76),
    ('nestjs', 'NestJS', 'nestjs', 'nestjs nest.js nest js', 'BACKEND', 83),
    ('express', 'Express.js', 'express.js', 'express express.js expressjs', 'BACKEND', 86),
    ('laravel', 'Laravel', 'laravel', 'laravel', 'BACKEND', 81),
    ('rails', 'Ruby on Rails', 'ruby on rails', 'ruby on rails rails', 'BACKEND', 67),
    ('gin', 'Gin', 'gin', 'gin gin gonic golang', 'BACKEND', 65),
    ('fiber', 'Fiber', 'fiber', 'fiber gofiber go fiber golang', 'BACKEND', 61),
    ('sql', 'SQL', 'sql', 'sql relational database', 'DATABASE', 97),
    ('postgresql', 'PostgreSQL', 'postgresql', 'postgresql postgres sql', 'DATABASE', 93),
    ('mysql', 'MySQL', 'mysql', 'mysql mariadb sql', 'DATABASE', 91),
    ('mssql', 'SQL Server', 'sql server', 'sql server mssql ms sql', 'DATABASE', 84),
    ('oracle', 'Oracle Database', 'oracle database', 'oracle database oracle db', 'DATABASE', 80),
    ('mongodb', 'MongoDB', 'mongodb', 'mongodb mongo nosql', 'DATABASE', 87),
    ('redis', 'Redis', 'redis', 'redis cache', 'DATABASE', 86),
    ('elasticsearch', 'Elasticsearch', 'elasticsearch', 'elasticsearch elastic search', 'DATABASE', 80),
    ('rest', 'REST API', 'rest api', 'rest rest api restful web api', 'ARCHITECTURE', 96),
    ('graphql', 'GraphQL', 'graphql', 'graphql', 'ARCHITECTURE', 78),
    ('grpc', 'gRPC', 'grpc', 'grpc', 'ARCHITECTURE', 73),
    ('microservices', 'Microservices', 'microservices', 'microservice microservices micro service', 'ARCHITECTURE', 90),
    ('distributed-systems', 'Distributed Systems', 'distributed systems', 'distributed systems distributed system', 'ARCHITECTURE', 78),
    ('oauth2', 'OAuth 2.0', 'oauth 2.0', 'oauth oauth2 oauth 2.0 openid connect oidc', 'SECURITY', 82),
    ('jwt', 'JWT', 'jwt', 'jwt json web token', 'SECURITY', 84),
    ('docker', 'Docker', 'docker', 'docker containerization container', 'DEVOPS', 94),
    ('kubernetes', 'Kubernetes', 'kubernetes', 'kubernetes k8s', 'DEVOPS', 89),
    ('linux', 'Linux', 'linux', 'linux ubuntu', 'DEVOPS', 91),
    ('cicd', 'CI/CD', 'ci/cd', 'ci/cd cicd continuous integration continuous delivery', 'DEVOPS', 90),
    ('git', 'Git', 'git', 'git github gitlab version control', 'TOOLING', 97),
    ('github-actions', 'GitHub Actions', 'github actions', 'github actions github ci', 'DEVOPS', 82),
    ('gitlab-ci', 'GitLab CI', 'gitlab ci', 'gitlab ci gitlab pipeline', 'DEVOPS', 76),
    ('jenkins', 'Jenkins', 'jenkins', 'jenkins ci', 'DEVOPS', 79),
    ('nginx', 'Nginx', 'nginx', 'nginx reverse proxy', 'DEVOPS', 82),
    ('aws', 'AWS', 'aws', 'aws amazon web services', 'CLOUD', 94),
    ('azure', 'Microsoft Azure', 'microsoft azure', 'azure microsoft azure', 'CLOUD', 87),
    ('gcp', 'Google Cloud Platform', 'google cloud platform', 'gcp google cloud google cloud platform', 'CLOUD', 84),
    ('terraform', 'Terraform', 'terraform', 'terraform infrastructure as code iac', 'DEVOPS', 85),
    ('ansible', 'Ansible', 'ansible', 'ansible', 'DEVOPS', 72),
    ('maven', 'Maven', 'maven', 'maven apache maven', 'TOOLING', 78),
    ('gradle', 'Gradle', 'gradle', 'gradle', 'TOOLING', 75),
    ('kafka', 'Apache Kafka', 'apache kafka', 'apache kafka kafka', 'DATA', 86),
    ('rabbitmq', 'RabbitMQ', 'rabbitmq', 'rabbitmq rabbit mq', 'BACKEND', 76),
    ('spark', 'Apache Spark', 'apache spark', 'apache spark spark pyspark', 'DATA', 80),
    ('airflow', 'Apache Airflow', 'apache airflow', 'apache airflow airflow', 'DATA', 76),
    ('pandas', 'Pandas', 'pandas', 'pandas python data', 'DATA', 80),
    ('numpy', 'NumPy', 'numpy', 'numpy python data', 'DATA', 79),
    ('tensorflow', 'TensorFlow', 'tensorflow', 'tensorflow machine learning', 'AI', 80),
    ('pytorch', 'PyTorch', 'pytorch', 'pytorch torch machine learning', 'AI', 82),
    ('scikit-learn', 'scikit-learn', 'scikit-learn', 'scikit-learn sklearn machine learning', 'AI', 78),
    ('machine-learning', 'Machine Learning', 'machine learning', 'machine learning ml', 'AI', 91),
    ('data-analysis', 'Data Analysis', 'data analysis', 'data analysis analytics', 'DATA', 87),
    ('flutter', 'Flutter', 'flutter', 'flutter mobile dart', 'MOBILE', 82),
    ('reactnative', 'React Native', 'react native', 'react native reactnative mobile', 'MOBILE', 81),
    ('android', 'Android', 'android', 'android mobile kotlin java', 'MOBILE', 84),
    ('ios', 'iOS', 'ios', 'ios mobile swift', 'MOBILE', 82),
    ('testing', 'Automated Testing', 'automated testing', 'unit testing integration testing automated testing tdd', 'QA', 89),
    ('junit', 'JUnit', 'junit', 'junit java testing', 'QA', 75),
    ('pytest', 'pytest', 'pytest', 'pytest python testing', 'QA', 75),
    ('selenium', 'Selenium', 'selenium', 'selenium testing', 'QA', 78),
    ('playwright', 'Playwright', 'playwright', 'playwright testing', 'QA', 80),
    ('cypress', 'Cypress', 'cypress', 'cypress testing', 'QA', 78),
    ('postman', 'Postman', 'postman', 'postman api testing', 'QA', 83),
    ('jira', 'Jira', 'jira', 'jira agile', 'TOOLING', 80),
    ('agile', 'Agile', 'agile', 'agile scrum kanban', 'PROCESS', 91),
    ('scrum', 'Scrum', 'scrum', 'scrum agile', 'PROCESS', 85),
    ('figma', 'Figma', 'figma', 'figma ui ux design', 'DESIGN', 83),
    ('ui-ux', 'UI/UX Design', 'ui/ux design', 'ui ux ui/ux design user experience', 'DESIGN', 84)
ON CONFLICT (canonical_key) DO UPDATE
SET name = EXCLUDED.name,
    normalized_name = EXCLUDED.normalized_name,
    search_text = EXCLUDED.search_text,
    category = EXCLUDED.category,
    popularity = EXCLUDED.popularity,
    is_active = TRUE,
    updated_at = NOW();
