global:
  scrape_interval: 15s

rule_files:
  - "rules.yml"

scrape_configs:
  - job_name: 'careerfit-backend'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['backend:8080']
