from pathlib import Path

from docx import Document
from docx.oxml.ns import qn
from docx.shared import Cm, Pt


REPORT = Path(r"C:\CODING\Thesis\Doc\CareerFit-Thesis-Report.docx")


def font(run, size=13):
    run.font.name = "Times New Roman"
    run.font.size = Pt(size)
    rpr = run._element.get_or_add_rPr()
    for key in ("w:ascii", "w:hAnsi", "w:eastAsia"):
        rpr.rFonts.set(qn(key), "Times New Roman")


def replace_last(doc, prefix, text):
    items = [p for p in doc.paragraphs if p.text.strip().startswith(prefix)]
    if not items:
        raise RuntimeError(prefix)
    p = items[-1]
    p.text = text
    for run in p.runs:
        font(run)


def cell(cell, text, bold=False):
    cell.text = ""
    p = cell.paragraphs[0]
    p.paragraph_format.first_line_indent = Cm(0)
    p.paragraph_format.space_after = Pt(0)
    p.paragraph_format.line_spacing = 1.0
    r = p.add_run(text)
    r.bold = bold
    font(r, 11)


def set_table(table, rows):
    while len(table.rows) < len(rows):
        table.add_row()
    while len(table.rows) > len(rows):
        table._tbl.remove(table.rows[-1]._tr)
    for ri, values in enumerate(rows):
        for ci, value in enumerate(values):
            cell(table.cell(ri, ci), value, ri == 0)


doc = Document(REPORT)
replace_last(doc, "Table 4.5.", "Table 4.5. Integrated Chrome workflow results")
replace_last(doc, "The controlled data lacks organic", "The controlled data lacks organic recruiter judgments, changing terminology, demographic diversity, adversarial behavior, and production class imbalance. The runtime is one Windows workstation with Docker Desktop, one local PostgreSQL instance, and desktop Chrome. Results cannot be generalized to enterprise load, other browsers, cloud deployment, or a population of real users.")
replace_last(doc, "The objective of providing role-specific", "The role-based workflow objective was achieved at prototype level. Guests can browse public Jobs and employers. Candidates can review CVs, inspect matching and recommendation results, apply or withdraw, submit feedback, and configure AutoFit. Recruiters can complete a company profile, manage Jobs, review applicants and the Talent Pool, bookmark or invite candidates, and update application states. Administrators can monitor users, Jobs, email actions, and audit records. The 41 Chrome tests cover representative flows but not every route or browser.")
replace_last(doc, "6. Show Actuator health", "6. Show Actuator health, the archived backend and Chrome test results, the benchmark artifact, and the final cleanup state.")

set_table(doc.tables[3], [
    ["Actor", "Primary responsibilities", "Access boundary"],
    ["Guest", "Browse public Jobs, suggestions, details, employers, urgent items, and public market analytics", "Public GET operations only; authentication is required for personalized data or applications"],
    ["Candidate", "Maintain profile and portfolio; draft/review/confirm CVs; view matches and recommendations; apply/withdraw; give feedback; configure AutoFit", "Candidate-owned resources and Candidate APIs"],
    ["Recruiter", "Maintain company profile and Jobs; review applicants/Talent Pool; bookmark and invite Candidates; update application states", "Recruiter APIs and Jobs owned by the authenticated Recruiter"],
    ["Administrator", "Monitor summaries, users, Jobs, email actions, and audit records; moderate Jobs and run controlled maintenance", "Administrative APIs only"],
    ["Background scheduler", "Recompute stale Matchings, send digests/reminders, clean expired actions, and run eligible automation", "Internal service calls under system control"],
    ["Mail provider", "Deliver notification and signed action emails generated by the backend", "SMTP boundary; it does not own CareerFit business state"],
])

set_table(doc.tables[29], [
    ["Question", "Evidence-supported answer"],
    ["Does Rocchio change holdout ranking in the intended direction?", "Yes for the controlled synthetic dataset; the same large metric delta was reproduced."],
    ["Is the backend automated suite passing?", "Yes. All 131 tests across 33 suites passed, and clean verify built the JAR."],
    ["Do the main browser workflows execute?", "Yes. All 41 integrated Chrome tests passed; Firefox/WebKit and participant UAT remain incomplete."],
    ["Are selected authorization boundaries enforced?", "Observed public, authentication, and role checks returned expected statuses; this is not comprehensive security validation."],
    ["Is the runtime healthy?", "Yes in the evaluated local profile: aggregate health, liveness, readiness, and the core API returned HTTP 200."],
    ["Is performance production-ready?", "Not evaluated. Only a small sequential localhost latency sample was collected."],
])

doc.save(REPORT)
print(REPORT)
