from pathlib import Path
from docx import Document

path = Path(__file__).resolve().parents[1] / "Doc" / "CareerFit-Thesis-Report.docx"
doc = Document(path)

exact = {
    28: "The system processes candidate profiles, curricula vitae, job descriptions, preferences, and user feedback. Textual information is normalized and represented with Term Frequency–Inverse Document Frequency vectors. Cosine similarity ranks CV–job pairs and candidate–job recommendations, while the Rocchio relevance-feedback method updates learned representations from explicit feedback. An AutoFit policy layer evaluates scores together with consent, thresholds, interaction history, quotas, cooldown rules, time zones, and quiet hours before selecting an action. Expiring email-action links use hashed token storage, a non-mutating confirmation request, and POST redemption. Audit records and action states support traceability and replay prevention.",
    29: "CareerFit is implemented as a role-based web platform for guests, candidates, recruiters, and administrators using a Spring Boot backend, a React and TypeScript frontend, and PostgreSQL persistence managed through Flyway migrations. The final backend suite passed 63 of 63 tests, the production frontend build completed with a largest JavaScript chunk of 375.64 kB, and four Chromium P0 workflows passed with cleanup of generated Job data. On a synthetic causal benchmark containing 50 Jobs and 100 CVs, Rocchio increased nDCG@5 from 0.037737 to 0.817737. The final benchmark log contained no optimistic-lock exception, and aggregate runtime health returned HTTP 200 with status UP. These results demonstrate controlled feedback behavior and integrated prototype workflows, not production hiring effectiveness.",
    346: "The email-action design uses two steps. GET hashes and validates the supplied high-entropy token and displays a confirmation page without changing recruitment state. A deliberate POST repeats validation, executes the supported action, marks the token as redeemed, and records the outcome. Only the SHA-256 token hash is persisted, while expiry and status checks prevent normal replay. Automated link scanners therefore cannot execute an action by merely visiting the GET URL.",
    341: "The scheduler contains five concrete tasks: stale Matching recomputation every 30 minutes; daily digest at 08:00 Asia/Ho_Chi_Minh; expired email-action cleanup at 03:00; high-match notification scans every four hours with an additional 07:00–22:00 ICT window; and auto-apply scans every two hours. The annotation expressions read their delays, cron expressions, and time zone from `app.scheduler.*` properties, providing one environment-configurable scheduling source.",
    384: "This chapter translated the CareerFit objectives into actors, functional groups, quality requirements, use cases, architecture, modules, data relationships, security boundaries, failure behavior, and deployment constraints. The implemented system is a modular monolith with a React client, Spring Boot backend, PostgreSQL/Flyway persistence, local CV storage, scheduled automation, and optional SMTP delivery. Matching evidence, application state, feedback, automation policy, and audit history are represented separately to preserve control and traceability. The hardened design uses confirm-then-POST email actions, hashed token storage, and externalized scheduler timing. Chapter 4 explains how the verified design is realized in code.",
    467: "This implementation removes the earlier state-changing GET and raw-token persistence findings. The remaining production concerns are rate limiting, deployment-specific link origin, secret rotation, mail-delivery monitoring, explicit handling of expired links, and protected audit review.",
    593: "This objective is achieved as configurable prototype automation. Notification policy and application authorization remain separate control paths, scheduler timing is externalized through `app.scheduler.*`, and the email-action channel uses hashed token storage with GET confirmation followed by POST execution. Further production work is still required for rate limiting, secret rotation, mail delivery, and deployment-specific origin controls.",
    622: "The final remediation pass resolved the observed optimistic-lock benchmark exception, scheduler/configuration drift, mock Job fallback values, persistent localStorage authentication, oversized frontend bundle warning, and missing E2E Job cleanup. Audit records are still written directly by multiple services, and the evaluated worktree is not an immutable release commit; those limitations weaken production operations and exact source-to-evidence reproducibility.",
    628: "Operational development should move CVs to protected object storage, define encryption and retention policy, centralize audit generation and redaction, strengthen token/session architecture, and associate each release with a clean commit and immutable evidence archive. Integration with external ATS or Job boards should occur only after consent, ownership, error recovery, and audit contracts are defined.",
}

for index, text in exact.items():
    p = doc.paragraphs[index]
    p.clear()
    p.add_run(text)

doc.save(path)
print(path)
